### ISSUE TITLE
fastbill_debug.log: failed to open stream

### ISSUE THREAD

**Issue by flowdee** [drumba/edd-fastbill#2]
Regularly getting the following php warning even when creating the log file it's gone some time later:

`PHP Warning:  fopen(/plugins/edd-fastbill/log/fastbill_debug.log): failed to open stream: No such file or directory in /plugins/edd-fastbill/includes/fastbill-functions.php on line 797`

I personally recommend logging via options and adding a reset log button on the settings. 👍

**Comment by mdrubba** [comment]
@flowdee what do you mean with "I personally recommend logging via options "

**Comment by flowdee** [comment]
Brief example from one of my projects:

```
/**
 * Output data to a log for debugging reasons
 **/
function my_addlog( $string ) {

    $datetime = get_date_from_gmt( date( 'Y-m-d H:i:s', time() ), 'd.m.Y H:i:s' );
    $string = $datetime . " >>> " . $string . "\n";

    $log = get_option( 'my_log', '' );
    $log .= $string;
    update_option( 'my_log', $log );
}
```

And afterwards im displaying the saved log output on the settings page of my plugin inside a textarea field. Followed by a button which allows resetting the log by deleting the option.

**Comment by flowdee** [comment]
already thought about how to solve this? my projects get spammed all the time with the errors 👎
